# Large Models Test Baseline

Closed-book API baseline for larger reference models on all 60 test problems. The default list is Qwen-family first, with DeepSeek left as an optional upper-bound comparison.

## Setup

This notebook currently uses OpenRouter's OpenAI-compatible API. Put `OPENROUTER_API_KEY=...` in the repo-local `.env` file.

In [20]:
!pip install -q -U openai pandas tqdm python-dotenv

In [21]:
from pathlib import Path
import json
import os
import sys
import time

from dotenv import load_dotenv
from openai import OpenAI
from tqdm.auto import tqdm

In [22]:
PROJECT_ROOT = Path("/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune")
sys.path.insert(0, str(PROJECT_ROOT))
load_dotenv(PROJECT_ROOT / ".env")
PROJECT_ROOT

PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune')

In [23]:
from training_eval.eval_utils import (
    GRADING_POLICY,
    default_test_dir,
    extract_answer,
    extract_json_object,
    is_correct,
    load_jsonl_records,
    make_closed_book_prompt,
    rows_to_frame,
    save_results,
    summarize_accuracy,
)

## Load Test Records

In [24]:
DATA_DIR = default_test_dir(PROJECT_ROOT)
records = load_jsonl_records(DATA_DIR, pattern="*_preview.jsonl")
len(records), DATA_DIR

(60,
 PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/benchmark/data/test'))

## Configure API Models

Now that the API has credit, the default references are larger Qwen-family models. Keep this list flexible: comment out anything slow, expensive, or rate-limited.

In [25]:
client = OpenAI(
    api_key=os.environ["OPENROUTER_API_KEY"],
    base_url="https://openrouter.ai/api/v1",
)

MODEL_NAMES = [
    "qwen/qwen3-8b",
    "qwen/qwen3-32b",
    "qwen/qwen3-235b-a22b",
    "deepseek/deepseek-v4-flash:free",
    "openai/gpt-oss-20b:free",
]

MAX_TOKENS = 128

RESET_OUTPUTS_BEFORE_RUN = True

RERUN_API_ERRORS = False
RERUN_OUTPUT_ERRORS = True
MAX_OUTPUT_RETRY_PASSES = 10
FILL_ONLY_EXISTING_EMPTY_OUTPUTS = False
STOP_MODEL_ON_RATE_LIMIT = True

In [26]:
def safe_model_name(model_name):
    return model_name.replace("-", "_").replace(".", "_").replace("/", "_").replace(":", "_")


def result_dir_for(model_name):
    return PROJECT_ROOT / "results" / "baselines" / f"{safe_model_name(model_name)}_test_closed_book_api"


def outputs_path_for(model_name):
    return result_dir_for(model_name) / "outputs.jsonl"


def load_cached_rows(model_name):
    path = outputs_path_for(model_name)
    if not path.exists():
        return []
    rows_by_id = {}
    with path.open() as f:
        for line in f:
            if line.strip():
                row = json.loads(line)
                rows_by_id[row["id"]] = row
    return list(rows_by_id.values())


def reset_model_outputs(model_names):
    for model_name in model_names:
        result_dir = result_dir_for(model_name)
        for filename in ["outputs.jsonl", "outputs.csv", "metrics.json"]:
            path = result_dir / filename
            if path.exists():
                path.unlink()


def append_cached_row(model_name, row):
    result_dir_for(model_name).mkdir(parents=True, exist_ok=True)
    with outputs_path_for(model_name).open("a") as f:
        f.write(json.dumps(row, sort_keys=True) + "\n")


def should_rerun_cached_row(row):
    if row.get("api_error"):
        return RERUN_API_ERRORS
    if row.get("output_error"):
        return RERUN_OUTPUT_ERRORS
    if RERUN_OUTPUT_ERRORS and not str(row.get("raw_output", "")).strip():
        return True
    if RERUN_OUTPUT_ERRORS and row.get("predicted_answer") is None:
        return True
    return False


def is_rate_limit_error(error_text):
    if not error_text:
        return False
    text = str(error_text).lower()
    return "429" in text or "rate limit" in text or "rate_limit" in text or "temporarily rate-limited" in text


def save_model_results(model_name, rows):
    df = rows_to_frame(rows)
    result_dir = result_dir_for(model_name)
    metrics = summarize_accuracy(df)
    metrics.update({
        "model": model_name,
        "provider": "openrouter",
        "dataset": "benchmark/data/test/*.jsonl",
        "num_api_errors": int(df["api_error"].notna().sum()) if "api_error" in df else 0,
        "num_output_errors": int(df["output_error"].notna().sum()) if "output_error" in df else 0,
        "num_empty_outputs": int(df["raw_output"].fillna("").astype(str).str.strip().eq("").sum()) if "raw_output" in df else 0,
        "checkpointed_after_each_record": True,
        "grading_policy": GRADING_POLICY,
    })
    return save_results(rows, result_dir, metrics)


def generate_answer(problem, model_name):
    response = client.chat.completions.create(
        model=model_name,
        messages=[{"role": "user", "content": make_closed_book_prompt(problem)}],
        temperature=0,
        max_tokens=MAX_TOKENS,
    )
    return response.choices[0].message.content or ""


def build_result_row(record, raw_output, predicted, api_error, output_error, correct):
    metadata = record.get("metadata", {})
    return {
        "id": record["id"],
        "family": record["family"],
        "problem_type": record["problem_type"],
        "difficulty": record["difficulty"],
        "manual_variation": metadata.get("manual_variation", False),
        "manual_problem_variation": metadata.get("manual_problem_variation", False),
        "manual_reasoning_variation": metadata.get("manual_reasoning_variation", False),
        "problem": record["problem"],
        "canonical_answer": record["canonical_answer"],
        "raw_output": raw_output,
        "predicted_answer": predicted,
        "api_error": api_error,
        "output_error": output_error,
        "correct": correct,
    }


def run_one_record(record, model_name):
    raw_output = ""
    predicted = None
    api_error = None
    output_error = None

    try:
        raw_output = generate_answer(record["problem"], model_name)
    except Exception as exc:
        api_error = repr(exc)
        return build_result_row(record, raw_output, predicted, api_error, output_error, False)

    if not raw_output.strip():
        output_error = "empty_response"
        return build_result_row(record, raw_output, predicted, api_error, output_error, False)

    predicted = extract_answer(raw_output, record["canonical_answer"])
    if predicted is None:
        output_error = "parse_failure"
        return build_result_row(record, raw_output, predicted, api_error, output_error, False)

    correct = is_correct(predicted, record["canonical_answer"])
    return build_result_row(record, raw_output, predicted, api_error, output_error, correct)

## One-Example Smoke Test

This runs the first dev record and writes it into the normal `outputs.jsonl` cache. The full run will skip it instead of spending the call again.

## Fresh Run Reset

When `RESET_OUTPUTS_BEFORE_RUN` is true, this clears cached API outputs before the smoke/full run. Use this for rigorous fresh baseline reruns.

In [27]:
if RESET_OUTPUTS_BEFORE_RUN:
    reset_model_outputs(MODEL_NAMES)

In [28]:
smoke_record = records[0]

for model_name in MODEL_NAMES:
    cached_rows = load_cached_rows(model_name)
    cached_by_id = {row["id"]: row for row in cached_rows if not should_rerun_cached_row(row)}

    print(model_name)
    if smoke_record["id"] in cached_by_id:
        row = cached_by_id[smoke_record["id"]]
        print("cached smoke result")
        print(row["raw_output"])
        print("predicted:", row["predicted_answer"])
        print("canonical:", row["canonical_answer"])
        print("correct:", row["correct"])
        print("api_error:", row.get("api_error"))
        print("output_error:", row.get("output_error"))
        print()
        continue

    row = run_one_record(smoke_record, model_name)
    append_cached_row(model_name, row)
    print(row["raw_output"])
    print("predicted:", row["predicted_answer"])
    print("canonical:", smoke_record["canonical_answer"])
    print("correct:", row["correct"])
    print("api_error:", row.get("api_error"))
    print("output_error:", row.get("output_error"))
    print()

qwen/qwen3-8b
<answer>{"expected_time": "21"}</answer>
predicted: {'expected_time': '21'}
canonical: {'expected_time': '21'}
correct: True
api_error: None
output_error: None

qwen/qwen3-32b
<answer>
{"expected_time": "21"}
</answer>
predicted: {'expected_time': '21'}
canonical: {'expected_time': '21'}
correct: True
api_error: None
output_error: None

qwen/qwen3-235b-a22b
<answer>
{"expected_time": "21"}
</answer>
predicted: {'expected_time': '21'}
canonical: {'expected_time': '21'}
correct: True
api_error: None
output_error: None

deepseek/deepseek-v4-flash:free

predicted: None
canonical: {'expected_time': '21'}
correct: False
api_error: RateLimitError("Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'deepseek/deepseek-v4-flash:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Crucible', 'is_byok': False}}, 'user_id': 'user_3DlCO9rhJDIH6DmLaQ6GxLR9UPC'}")
output_error: None

openai/gpt-oss-20b:free
<answer>{"expected_time":"21"}</answer>
predicted: {'expected_time': '21'}
canonical: {'expected_time': '21'}
correct: True
api_error: None
output_error: None

## Run Full Test Evaluation

This cell is safe to use with **Run All** for a rigorous baseline.

It skips terminal cached rows, runs missing rows, and checkpoints each completed row immediately to `outputs.jsonl`. Non-API issues such as schema aliases are handled by the shared tolerant grader.

API failures are recorded with `api_error` and are not retried. Output failures that are not API failures, such as empty responses or unparsable JSON, are retried for up to `MAX_OUTPUT_RETRY_PASSES` passes. If only API-failed rows remain, the model is considered done for this run.

In [29]:
all_results = {}


def runnable_rows_for(model_name):
    cached_rows = load_cached_rows(model_name)
    terminal_rows = [row for row in cached_rows if not should_rerun_cached_row(row)]
    terminal_ids = {row["id"] for row in terminal_rows}
    unfinished = [record for record in records if record["id"] not in terminal_ids]
    return cached_rows, terminal_rows, terminal_ids, unfinished


for model_name in MODEL_NAMES:
    model_hit_rate_limit = False

    for pass_idx in range(1, MAX_OUTPUT_RETRY_PASSES + 1):
        cached_rows, rows, completed_ids, unfinished = runnable_rows_for(model_name)

        if not unfinished:
            print(f"{model_name}: complete ({len(completed_ids)}/{len(records)})")
            all_results[model_name] = rows
            break

        print(f"{model_name}: pass {pass_idx}/{MAX_OUTPUT_RETRY_PASSES}; {len(completed_ids)}/{len(records)} terminal rows, {len(unfinished)} rows to run/retry")

        for record in tqdm(unfinished):
            row = run_one_record(record, model_name)
            rows.append(row)
            append_cached_row(model_name, row)

            if row.get("api_error"):
                print(f"API issue for {model_name} on {record['id']}: {row['api_error']}")
            elif row.get("output_error"):
                print(f"Output issue for {model_name} on {record['id']}: {row['output_error']}")

            if STOP_MODEL_ON_RATE_LIMIT and is_rate_limit_error(row.get("api_error")):
                print(f"Giving up on {model_name} for this run after rate-limit error on {record['id']}")
                model_hit_rate_limit = True
                break

        rows = load_cached_rows(model_name)
        save_model_results(model_name, rows)
        all_results[model_name] = rows

        if model_hit_rate_limit:
            break

    else:
        cached_rows, rows, completed_ids, unfinished = runnable_rows_for(model_name)
        print(f"{model_name}: reached MAX_OUTPUT_RETRY_PASSES with {len(unfinished)} non-terminal rows still unresolved")
        all_results[model_name] = rows

print("Baseline run finished. API failures were saved and not retried; output failures were retried before giving up.")

qwen/qwen3-8b: pass 1/10; 1/60 terminal rows, 59 rows to run/retry

100%|██████████| 59/59 [34:51<00:00, 35.45s/it]

qwen/qwen3-8b: complete (60/60)
qwen/qwen3-32b: pass 1/10; 1/60 terminal rows, 59 rows to run/retry

  2%|▏         | 1/59 [00:01<01:48,  1.87s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004101: empty_response

  3%|▎         | 2/59 [00:03<01:52,  1.97s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004102: empty_response

  8%|▊         | 5/59 [00:07<01:22,  1.53s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004200: empty_response

 10%|█         | 6/59 [00:13<02:25,  2.75s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004201: empty_response

 12%|█▏        | 7/59 [00:15<02:14,  2.59s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004202: empty_response

 17%|█▋        | 10/59 [03:04<30:03, 36.80s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004300: empty_response

 20%|██        | 12/59 [14:43<2:10:39, 166.80s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004302: empty_response

 22%|██▏       | 13/59 [14:45<1:29:49, 117.17s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004303: empty_response

 24%|██▎       | 14/59 [14:48<1:01:50, 82.46s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004304: empty_response

 27%|██▋       | 16/59 [14:57<30:27, 42.50s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001101: empty_response

 29%|██▉       | 17/59 [14:59<21:16, 30.40s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001102: empty_response

 31%|███       | 18/59 [15:02<15:06, 22.11s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001103: empty_response

 37%|███▋      | 22/59 [15:46<08:30, 13.81s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001202: empty_response

 39%|███▉      | 23/59 [15:49<06:20, 10.56s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001203: empty_response

 41%|████      | 24/59 [15:52<04:49,  8.26s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001204: empty_response

 42%|████▏     | 25/59 [15:55<03:48,  6.71s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001300: empty_response

 44%|████▍     | 26/59 [15:57<02:52,  5.23s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001301: empty_response

 46%|████▌     | 27/59 [16:00<02:25,  4.54s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001302: empty_response

 47%|████▋     | 28/59 [16:03<02:07,  4.11s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001303: empty_response

 49%|████▉     | 29/59 [16:05<01:42,  3.40s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001304: empty_response

 51%|█████     | 30/59 [16:06<01:22,  2.85s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002100: empty_response

 54%|█████▍    | 32/59 [16:09<00:56,  2.09s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002102: empty_response

 56%|█████▌    | 33/59 [16:12<01:00,  2.32s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002103: empty_response

 64%|██████▍   | 38/59 [16:56<02:16,  6.52s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002203: empty_response

 68%|██████▊   | 40/59 [17:37<03:49, 12.06s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002300: empty_response

 69%|██████▉   | 41/59 [17:39<02:40,  8.90s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002301: empty_response

 71%|███████   | 42/59 [17:42<02:03,  7.27s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002302: empty_response

 75%|███████▍  | 44/59 [17:45<01:06,  4.42s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002304: empty_response

 76%|███████▋  | 45/59 [17:47<00:50,  3.60s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003100: empty_response

 78%|███████▊  | 46/59 [17:49<00:38,  2.97s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003101: empty_response

 81%|████████▏ | 48/59 [18:57<02:55, 15.95s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003103: empty_response

 83%|████████▎ | 49/59 [19:03<02:09, 12.95s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003104: empty_response

 85%|████████▍ | 50/59 [19:04<01:25,  9.53s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003200: empty_response

 88%|████████▊ | 52/59 [19:34<01:20, 11.48s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003202: empty_response

 90%|████████▉ | 53/59 [19:37<00:53,  8.86s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003203: empty_response

 93%|█████████▎| 55/59 [19:53<00:31,  7.91s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003300: empty_response

 97%|█████████▋| 57/59 [21:23<00:46, 23.12s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003302: empty_response

100%|██████████| 59/59 [21:47<00:00, 22.15s/it]

qwen/qwen3-32b: pass 2/10; 23/60 terminal rows, 37 rows to run/retry

  3%|▎         | 1/37 [00:02<01:45,  2.93s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004101: empty_response

  8%|▊         | 3/37 [00:10<02:12,  3.89s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004200: empty_response

 24%|██▍       | 9/37 [10:29<48:07, 103.11s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004304: empty_response

 30%|██▉       | 11/37 [10:46<23:05, 53.28s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001102: empty_response

 35%|███▌      | 13/37 [10:53<11:07, 27.82s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001202: empty_response

 38%|███▊      | 14/37 [10:55<07:41, 20.05s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001203: empty_response

 41%|████      | 15/37 [11:08<06:35, 17.99s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001204: empty_response

 49%|████▊     | 18/37 [11:42<03:38, 11.48s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001302: empty_response

 51%|█████▏    | 19/37 [11:45<02:37,  8.73s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001303: empty_response

 54%|█████▍    | 20/37 [11:46<01:52,  6.64s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001304: empty_response

 57%|█████▋    | 21/37 [11:48<01:24,  5.26s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002100: empty_response

 65%|██████▍   | 24/37 [12:12<01:15,  5.79s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002203: empty_response

 68%|██████▊   | 25/37 [12:13<00:54,  4.52s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002300: empty_response

 73%|███████▎  | 27/37 [12:23<00:49,  4.92s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002302: empty_response

 76%|███████▌  | 28/37 [12:25<00:36,  4.03s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002304: empty_response

 78%|███████▊  | 29/37 [12:32<00:40,  5.11s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003100: empty_response

 81%|████████  | 30/37 [12:34<00:29,  4.25s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003101: empty_response

 84%|████████▍ | 31/37 [12:36<00:20,  3.44s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003103: empty_response

 86%|████████▋ | 32/37 [12:38<00:14,  2.92s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003104: empty_response

 92%|█████████▏| 34/37 [13:06<00:24,  8.15s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003202: empty_response

100%|██████████| 37/37 [13:10<00:00, 21.36s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003302: empty_response
qwen/qwen3-32b: pass 3/10; 39/60 terminal rows, 21 rows to run/retry

  5%|▍         | 1/21 [00:01<00:29,  1.47s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004101: empty_response

 10%|▉         | 2/21 [00:02<00:26,  1.40s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004200: empty_response

 14%|█▍        | 3/21 [00:04<00:28,  1.61s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004304: empty_response

 33%|███▎      | 7/21 [00:40<01:38,  7.03s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001204: empty_response

 43%|████▎     | 9/21 [00:59<01:33,  7.82s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001303: empty_response

 48%|████▊     | 10/21 [01:02<01:08,  6.25s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001304: empty_response

 52%|█████▏    | 11/21 [01:04<00:49,  4.93s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002100: empty_response

 57%|█████▋    | 12/21 [01:07<00:38,  4.27s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002203: empty_response

 62%|██████▏   | 13/21 [01:09<00:27,  3.47s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002300: empty_response

 67%|██████▋   | 14/21 [01:10<00:20,  2.89s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002302: empty_response

 71%|███████▏  | 15/21 [01:12<00:14,  2.45s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002304: empty_response

 76%|███████▌  | 16/21 [01:13<00:10,  2.15s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003100: empty_response

 86%|████████▌ | 18/21 [01:29<00:14,  4.91s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003103: empty_response

 90%|█████████ | 19/21 [01:35<00:10,  5.16s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003104: empty_response

100%|██████████| 21/21 [02:23<00:00,  6.85s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003302: empty_response
qwen/qwen3-32b: pass 4/10; 45/60 terminal rows, 15 rows to run/retry

  7%|▋         | 1/15 [00:10<02:29, 10.69s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004101: empty_response

 13%|█▎        | 2/15 [00:12<01:08,  5.29s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004200: empty_response

 20%|██        | 3/15 [00:15<00:52,  4.36s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004304: empty_response

 33%|███▎      | 5/15 [00:28<00:52,  5.25s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001303: empty_response

 40%|████      | 6/15 [00:31<00:39,  4.41s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001304: empty_response

 47%|████▋     | 7/15 [00:33<00:30,  3.78s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002100: empty_response

 53%|█████▎    | 8/15 [00:35<00:23,  3.32s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002203: empty_response

 60%|██████    | 9/15 [00:38<00:19,  3.18s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002300: empty_response

 73%|███████▎  | 11/15 [00:49<00:15,  3.97s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002304: empty_response

 80%|████████  | 12/15 [00:53<00:12,  4.10s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003100: empty_response

 87%|████████▋ | 13/15 [00:59<00:09,  4.56s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003103: empty_response

 93%|█████████▎| 14/15 [01:05<00:04,  4.88s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003104: empty_response

100%|██████████| 15/15 [01:11<00:00,  4.74s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003302: empty_response
qwen/qwen3-32b: pass 5/10; 47/60 terminal rows, 13 rows to run/retry

 23%|██▎       | 3/13 [02:03<06:10, 37.06s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004304: empty_response

 31%|███       | 4/13 [02:05<03:27, 23.11s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001303: empty_response

 54%|█████▍    | 7/13 [02:45<01:23, 13.96s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002203: empty_response

 62%|██████▏   | 8/13 [02:48<00:52, 10.42s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002300: empty_response

 77%|███████▋  | 10/13 [02:49<00:15,  5.32s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003100: empty_response

 85%|████████▍ | 11/13 [02:52<00:09,  4.54s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003103: empty_response

 92%|█████████▏| 12/13 [03:08<00:08,  8.07s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003104: empty_response

100%|██████████| 13/13 [03:19<00:00, 15.34s/it]

qwen/qwen3-32b: pass 6/10; 53/60 terminal rows, 7 rows to run/retry

 14%|█▍        | 1/7 [00:01<00:10,  1.75s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004304: empty_response

 29%|██▊       | 2/7 [00:03<00:08,  1.65s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001303: empty_response

 57%|█████▋    | 4/7 [00:07<00:05,  1.94s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002300: empty_response

100%|██████████| 7/7 [00:22<00:00,  3.24s/it]

Output issue for qwen/qwen3-32b on stopped_process_expectation_dev_003104: empty_response
qwen/qwen3-32b: pass 7/10; 56/60 terminal rows, 4 rows to run/retry

 25%|██▌       | 1/4 [00:01<00:05,  1.97s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004304: empty_response

 50%|█████     | 2/4 [00:03<00:03,  1.89s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001303: empty_response

 75%|███████▌  | 3/4 [00:15<00:06,  6.37s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002300: empty_response

100%|██████████| 4/4 [01:15<00:00, 18.75s/it]

qwen/qwen3-32b: pass 8/10; 57/60 terminal rows, 3 rows to run/retry

 33%|███▎      | 1/3 [00:02<00:05,  2.88s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004304: empty_response

 67%|██████▋   | 2/3 [00:05<00:02,  2.79s/it]

Output issue for qwen/qwen3-32b on martingale_verification_dev_001303: empty_response

100%|██████████| 3/3 [00:07<00:00,  2.47s/it]

Output issue for qwen/qwen3-32b on optional_stopping_validity_dev_002300: empty_response
qwen/qwen3-32b: pass 9/10; 57/60 terminal rows, 3 rows to run/retry

 33%|███▎      | 1/3 [00:11<00:23, 11.95s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004304: empty_response

100%|██████████| 3/3 [00:56<00:00, 18.98s/it]

qwen/qwen3-32b: pass 10/10; 59/60 terminal rows, 1 rows to run/retry

100%|██████████| 1/1 [00:06<00:00,  6.52s/it]

Output issue for qwen/qwen3-32b on hitting_time_expectation_dev_004304: empty_response
qwen/qwen3-32b: reached MAX_OUTPUT_RETRY_PASSES with 1 non-terminal rows still unresolved
qwen/qwen3-235b-a22b: pass 1/10; 1/60 terminal rows, 59 rows to run/retry

100%|██████████| 59/59 [21:46<00:00, 22.14s/it]

qwen/qwen3-235b-a22b: complete (60/60)
deepseek/deepseek-v4-flash:free: pass 1/10; 1/60 terminal rows, 59 rows to run/retry

  0%|          | 0/59 [00:03<?, ?it/s]

API issue for deepseek/deepseek-v4-flash:free on hitting_time_expectation_dev_004101: RateLimitError("Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'deepseek/deepseek-v4-flash:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Crucible', 'is_byok': False}}, 'user_id': 'user_3DlCO9rhJDIH6DmLaQ6GxLR9UPC'}")
Giving up on deepseek/deepseek-v4-flash:free for this run after rate-limit error on hitting_time_expectation_dev_004101
openai/gpt-oss-20b:free: pass 1/10; 1/60 terminal rows, 59 rows to run/retry

 34%|███▍      | 20/59 [04:43<06:30, 10.02s/it]

Output issue for openai/gpt-oss-20b:free on martingale_verification_dev_001200: parse_failure

 76%|███████▋  | 45/59 [12:34<18:58, 81.29s/it]

Output issue for openai/gpt-oss-20b:free on stopped_process_expectation_dev_003100: empty_response

100%|██████████| 59/59 [14:29<00:00, 14.74s/it]

openai/gpt-oss-20b:free: pass 2/10; 58/60 terminal rows, 2 rows to run/retry

100%|██████████| 2/2 [01:19<00:00, 39.62s/it]

openai/gpt-oss-20b:free: complete (60/60)
Baseline run finished. API failures were saved and not retried; output failures were retried before giving up.

## Metrics

In [30]:
{model: len(rows) for model, rows in all_results.items()} if "all_results" in globals() else {}

{'qwen/qwen3-8b': 60,
 'qwen/qwen3-32b': 59,
 'qwen/qwen3-235b-a22b': 60,
 'deepseek/deepseek-v4-flash:free': 2,
 'openai/gpt-oss-20b:free': 60}

In [31]:
for model_name, rows in all_results.items():
    df = rows_to_frame(rows)
    print(model_name)
    print(f"Overall accuracy: {df['correct'].mean():.3f} ({df['correct'].sum()}/{len(df)})")
    display(df.groupby("family")["correct"].agg(["mean", "sum", "count"]).sort_index())
    display(df.groupby("difficulty")["correct"].agg(["mean", "sum", "count"]).sort_index())
    display(df.groupby("manual_variation")["correct"].agg(["mean", "sum", "count"]).sort_index())
    print()

qwen/qwen3-8b
Overall accuracy: 0.967 (58/60)

                                 mean  sum  count
family
hitting_time_expectation     0.933333   14     15
martingale_verification      1.000000   15     15
optional_stopping_validity   1.000000   15     15
stopped_process_expectation  0.933333   14     15

            mean  sum  count
difficulty
1           1.00   20     20
2           0.95   19     20
3           0.95   19     20

                      mean  sum  count
manual_variation
False             1.000000   24     24
True              0.944444   34     36

qwen/qwen3-32b
Overall accuracy: 0.831 (49/59)

                                 mean  sum  count
family
hitting_time_expectation     0.714286   10     14
martingale_verification      0.933333   14     15
optional_stopping_validity   0.933333   14     15
stopped_process_expectation  0.733333   11     15

                mean  sum  count
difficulty
1           0.750000   15     20
2           0.950000   19     20
3           0.789474   15     19

                      mean  sum  count
manual_variation
False             0.833333   20     24
True              0.828571   29     35

qwen/qwen3-235b-a22b
Overall accuracy: 0.967 (58/60)

                                 mean  sum  count
family
hitting_time_expectation     1.000000   15     15
martingale_verification      1.000000   15     15
optional_stopping_validity   0.933333   14     15
stopped_process_expectation  0.933333   14     15

            mean  sum  count
difficulty
1           0.95   19     20
2           0.95   19     20
3           1.00   20     20

                      mean  sum  count
manual_variation
False             1.000000   24     24
True              0.944444   34     36

deepseek/deepseek-v4-flash:free
Overall accuracy: 0.000 (0/2)

                          mean  sum  count
family
hitting_time_expectation   0.0    0      2

            mean  sum  count
difficulty
1            0.0    0      2

                  mean  sum  count
manual_variation
True               0.0    0      2

openai/gpt-oss-20b:free
Overall accuracy: 0.900 (54/60)

                                 mean  sum  count
family
hitting_time_expectation     0.866667   13     15
martingale_verification      1.000000   15     15
optional_stopping_validity   1.000000   15     15
stopped_process_expectation  0.733333   11     15

            mean  sum  count
difficulty
1           0.95   19     20
2           0.85   17     20
3           0.90   18     20

                      mean  sum  count
manual_variation
False             0.875000   21     24
True              0.916667   33     36

## Save Results

In [32]:
saved_paths = {}

for model_name, rows in all_results.items():
    saved_paths[model_name] = save_model_results(model_name, rows)

saved_paths

{'qwen/qwen3-8b': (PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/baselines/qwen_qwen3_8b_test_closed_book_api/outputs.jsonl'),
  PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/baselines/qwen_qwen3_8b_test_closed_book_api/metrics.json'),
  PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/baselines/qwen_qwen3_8b_test_closed_book_api/outputs.csv')),
 'qwen/qwen3-32b': (PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/baselines/qwen_qwen3_32b_test_closed_book_api/outputs.jsonl'),
  PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/baselines/qwen_qwen3_32b_test_closed_book_api/metrics.json'),
  PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/baselines/qwen_qwen3_32b_test_closed_book_api/outputs.csv')),
 'qwen/qwen3-235b-a22b': (PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/baselines/qwen_qwen3_235b_a22b_test_closed_book_api/outputs.jsonl'),
  PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/baselines/qwen_qwen3_235b_a22b_test_closed_book_api/metrics.json'),
  PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/baselines/qwen_qwen3_235b_a22b_test_closed_book_api/outputs.csv')),
 'deepseek/deepseek-v4-flash:free': (PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/baselines/deepseek_deepseek_v4_flash_free_test_closed_book_api/outputs.jsonl'),
  PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/baselines/deepseek_deepseek_v4_flash_free_test_closed_book_api/metrics.json'),
  PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/baselines/deepseek_deepseek_v4_flash_free_test_closed_book_api/outputs.csv')),
 'openai/gpt-oss-20b:free': (PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/baselines/openai_gpt_oss_20b_free_test_closed_book_api/outputs.jsonl'),
  PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/baselines/openai_gpt_oss_20b_free_test_closed_book_api/metrics.json'),
  PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/baselines/openai_gpt_oss_20b_free_test_closed_book_api/outputs.csv'))}

## Inspect Mistakes

In [33]:
available_models = [model_name for model_name, rows in all_results.items() if rows]
available_models

['qwen/qwen3-8b',
 'qwen/qwen3-32b',
 'qwen/qwen3-235b-a22b',
 'deepseek/deepseek-v4-flash:free',
 'openai/gpt-oss-20b:free']

In [34]:
model_name = available_models[-1]
df = rows_to_frame(all_results[model_name])
df.loc[~df["correct"], [
    "id",
    "family",
    "problem_type",
    "difficulty",
    "canonical_answer",
    "predicted_answer",
    "api_error",
    "raw_output",
]].head(20)

,id,family,problem_type,difficulty,canonical_answer,predicted_answer,api_error,raw_output
11,hitting_time_expectation_dev_004301,hitting_time_expectation,biased_boundaries_zero_a,3,{'expected_time': '22980/2059'},{'expected_time': '11.16'},None,"<answer>{""expected_time"":""11.16""}"
13,hitting_time_expectation_dev_004303,hitting_time_expectation,biased_boundaries_zero_a,3,{'expected_time': '1265/211'},{'expected_time': '6.0'},None,"<answer>{""expected_time"":""6.0""}</answer>"
45,stopped_process_expectation_dev_003100,stopped_process_expectation,bounded_walk_expectation,1,{'value': '2'},{'value': '2.0'},None,"<answer>{""value"":""2.0""}</answer>"
52,stopped_process_expectation_dev_003202,stopped_process_expectation,quadratic_fixed_horizon,2,{'value': '84'},{'value': '67'},None,"<answer>{""value"":""67""}</answer>"
53,stopped_process_expectation_dev_003203,stopped_process_expectation,quadratic_fixed_horizon,2,{'value': '11'},{'E[S_10^2]': 11},None,"<answer>{\n ""E[S_10^2]"": 11\n}</answer>"
54,stopped_process_expectation_dev_003204,stopped_process_expectation,quadratic_fixed_horizon,2,{'value': '72'},{'value': '63'},None,"<answer>{""value"":""63""}</answer>"