# Train Qwen3 1.7B LoRA Adapters

Train local LoRA adapters for the current formula-direct and algorithmic-scaffold teaching variants.

In [13]:
!pip install -q -U "mlx-lm[train]" pandas tqdm

In [14]:
from pathlib import Path
import json
import shlex
import shutil
import subprocess
import sys

In [15]:
PROJECT_ROOT = Path("/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune")
sys.path.insert(0, str(PROJECT_ROOT))
PROJECT_ROOT

PosixPath('/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune')

In [16]:
MODEL_NAME = "Qwen/Qwen3-1.7B-MLX-bf16"
DATA_ROOT = PROJECT_ROOT / "training_eval" / "fine_tune_qwen1_7B" / "lora" / "data"
RESULT_ROOT = PROJECT_ROOT / "results" / "fine_tunes" / "qwen3_1_7b_lora"

In [17]:
ITERS = 1500
BATCH_SIZE = 1
GRAD_ACCUMULATION_STEPS = 8
NUM_LAYERS = 12
LEARNING_RATE = "1e-5"
RESET_ADAPTERS_BEFORE_TRAINING = True
SKIP_IF_ADAPTER_EXISTS = False

In [18]:
EXPERIMENTS = {
    "formula_direct": {
        "data_dir": DATA_ROOT / "formula_direct",
        "adapter_path": RESULT_ROOT / "formula_direct" / "adapters",
    },
    "algorithmic_scaffold": {
        "data_dir": DATA_ROOT / "algorithmic_scaffold",
        "adapter_path": RESULT_ROOT / "algorithmic_scaffold" / "adapters",
    },
    "algorithmic_scaffold_v2": {
        "data_dir": DATA_ROOT / "algorithmic_scaffold_v2",
        "adapter_path": RESULT_ROOT / "algorithmic_scaffold_v2" / "adapters",
    },
    "algorithmic_scaffold_v2_5": {
        "data_dir": DATA_ROOT / "algorithmic_scaffold_v2_5",
        "adapter_path": RESULT_ROOT / "algorithmic_scaffold_v2_5" / "adapters",
    },
    "algorithmic_scaffold_v3": {
        "data_dir": DATA_ROOT / "algorithmic_scaffold_v3",
        "adapter_path": RESULT_ROOT / "algorithmic_scaffold_v3" / "adapters",
    },
    "algorithmic_scaffold_v3_1": {
        "data_dir": DATA_ROOT / "algorithmic_scaffold_v3_1",
        "adapter_path": RESULT_ROOT / "algorithmic_scaffold_v3_1" / "adapters",
    },
    "algorithmic_scaffold_v3_1_lora8": {
        "data_dir": DATA_ROOT / "algorithmic_scaffold_v3_1",
        "adapter_path": RESULT_ROOT / "algorithmic_scaffold_v3_1_lora8" / "adapters",
    },
    "algorithmic_scaffold_v3_5": {
        "data_dir": DATA_ROOT / "algorithmic_scaffold_v3_5",
        "adapter_path": RESULT_ROOT / "algorithmic_scaffold_v3_5" / "adapters",
    },
    "algorithmic_scaffold_v3_5_lora12": {
        "data_dir": DATA_ROOT / "algorithmic_scaffold_v3_5",
        "adapter_path": RESULT_ROOT / "algorithmic_scaffold_v3_5_lora12" / "adapters",
    },
}

# Keep this list small while iterating locally. Explicit/implicit theorem adapters
# are intentionally suppressed for now to save runtime.
EXPERIMENTS_TO_RUN = ["algorithmic_scaffold_v3_5_lora12"]
ACTIVE_EXPERIMENTS = {name: EXPERIMENTS[name] for name in EXPERIMENTS_TO_RUN}

In [19]:
def make_lora_command(data_dir, adapter_path):
    return [
        sys.executable,
        "-m",
        "mlx_lm.lora",
        "--model",
        MODEL_NAME,
        "--train",
        "--data",
        str(data_dir),
        "--adapter-path",
        str(adapter_path),
        "--iters",
        str(ITERS),
        "--batch-size",
        str(BATCH_SIZE),
        "--grad-accumulation-steps",
        str(GRAD_ACCUMULATION_STEPS),
        "--num-layers",
        str(NUM_LAYERS),
        "--learning-rate",
        LEARNING_RATE,
        "--mask-prompt",
        "--grad-checkpoint",
    ]

In [20]:
def adapter_exists(adapter_path):
    return (adapter_path / "adapters.safetensors").exists() or (adapter_path / "adapters.npz").exists()

In [21]:
def reset_adapter_dir(config):
    if config["adapter_path"].exists():
        shutil.rmtree(config["adapter_path"])

In [22]:
def run_lora_training(name, config):
    if SKIP_IF_ADAPTER_EXISTS and adapter_exists(config["adapter_path"]):
        print(f"Skipping {name}; adapter already exists at {config['adapter_path']}")
        return

    config["adapter_path"].mkdir(parents=True, exist_ok=True)
    command = make_lora_command(config["data_dir"], config["adapter_path"])
    print(shlex.join(command))
    subprocess.run(command, check=True)

## Smoke Train

Run this first if you want a quick command check for the first active adapter.

In [23]:
RUN_SMOKE = False

if RUN_SMOKE:
    smoke_name = EXPERIMENTS_TO_RUN[0]
    run_lora_training(smoke_name, EXPERIMENTS[smoke_name])

## Active Training Run

Runs only the adapters listed in `EXPERIMENTS_TO_RUN`.

In [24]:
RUN_TRAINING = True

if RUN_TRAINING:
    for name, config in ACTIVE_EXPERIMENTS.items():
        run_lora_training(name, config)

/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/.venv/bin/python -m mlx_lm.lora --model Qwen/Qwen3-1.7B-MLX-bf16 --train --data /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/training_eval/fine_tune_qwen1_7B/lora/data/algorithmic_scaffold_v3_5 --adapter-path /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters --iters 1500 --batch-size 1 --grad-accumulation-steps 8 --num-layers 12 --learning-rate 1e-5 --mask-prompt --grad-checkpoint
Calling `python -m mlx_lm.lora...` directly is deprecated. Use `mlx_lm.lora...` or `python -m mlx_lm lora ...` instead.
Loading pretrained model

Fetching 7 files: 100%|██████████| 7/7 [00:00<00:00, 90617.68it/s]

Loading datasets
Training
Trainable parameters: 0.217% (3.736M/1720.575M)
Starting training..., iters: 1500

Calculating loss...: 100%|██████████| 25/25 [00:13<00:00,  1.79it/s]

Iter 1: Val loss 3.723, Val took 13.950s
Iter 10: Train loss 3.234, Learning Rate 1.000e-05, It/sec 0.546, Tokens/sec 134.185, Trained Tokens 2459, Peak mem 4.594 GB
Iter 20: Train loss 2.514, Learning Rate 1.000e-05, It/sec 0.460, Tokens/sec 129.755, Trained Tokens 5277, Peak mem 4.607 GB
Iter 30: Train loss 2.431, Learning Rate 1.000e-05, It/sec 0.589, Tokens/sec 123.244, Trained Tokens 7370, Peak mem 4.609 GB
Iter 40: Train loss 1.917, Learning Rate 1.000e-05, It/sec 0.789, Tokens/sec 123.827, Trained Tokens 8940, Peak mem 4.609 GB
Iter 50: Train loss 2.093, Learning Rate 1.000e-05, It/sec 0.833, Tokens/sec 98.558, Trained Tokens 10123, Peak mem 4.609 GB
Iter 60: Train loss 1.549, Learning Rate 1.000e-05, It/sec 0.598, Tokens/sec 110.629, Trained Tokens 11973, Peak mem 4.609 GB
Iter 70: Train loss 1.303, Learning Rate 1.000e-05, It/sec 0.650, Tokens/sec 111.024, Trained Tokens 13682, Peak mem 4.609 GB
Iter 80: Train loss 1.236, Learning Rate 1.000e-05, It/sec 0.732, Tokens/sec 122.863, Trained Tokens 15361, Peak mem 4.609 GB
Iter 90: Train loss 1.241, Learning Rate 1.000e-05, It/sec 0.641, Tokens/sec 128.754, Trained Tokens 17369, Peak mem 4.609 GB
Iter 100: Train loss 1.164, Learning Rate 1.000e-05, It/sec 0.611, Tokens/sec 130.538, Trained Tokens 19506, Peak mem 4.609 GB
Iter 100: Saved adapter weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors and /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/0000100_adapters.safetensors.
Iter 110: Train loss 1.103, Learning Rate 1.000e-05, It/sec 0.782, Tokens/sec 115.252, Trained Tokens 20979, Peak mem 4.609 GB
Iter 120: Train loss 1.234, Learning Rate 1.000e-05, It/sec 0.615, Tokens/sec 127.627, Trained Tokens 23055, Peak mem 4.624 GB
Iter 130: Train loss 1.129, Learning Rate 1.000e-05, It/sec 0.642, Tokens/sec 122.428, Trained Tokens 24963, Peak mem 4.624 GB
Iter 140: Train loss 1.121, Learning Rate 1.000e-05, It/sec 0.673, Tokens/sec 110.606, Trained Tokens 26606, Peak mem 4.624 GB
Iter 150: Train loss 0.941, Learning Rate 1.000e-05, It/sec 0.637, Tokens/sec 131.834, Trained Tokens 28677, Peak mem 4.624 GB
Iter 160: Train loss 0.859, Learning Rate 1.000e-05, It/sec 0.662, Tokens/sec 117.971, Trained Tokens 30460, Peak mem 4.624 GB
Iter 170: Train loss 0.898, Learning Rate 1.000e-05, It/sec 0.654, Tokens/sec 116.827, Trained Tokens 32247, Peak mem 4.624 GB
Iter 180: Train loss 0.831, Learning Rate 1.000e-05, It/sec 0.753, Tokens/sec 111.438, Trained Tokens 33727, Peak mem 4.624 GB
Iter 190: Train loss 0.924, Learning Rate 1.000e-05, It/sec 0.478, Tokens/sec 136.622, Trained Tokens 36585, Peak mem 4.624 GB

Calculating loss...: 100%|██████████| 25/25 [00:18<00:00,  1.35it/s]

Iter 200: Val loss 0.830, Val took 18.555s
Iter 200: Train loss 0.828, Learning Rate 1.000e-05, It/sec 0.706, Tokens/sec 119.255, Trained Tokens 38274, Peak mem 4.624 GB
Iter 200: Saved adapter weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors and /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/0000200_adapters.safetensors.
Iter 210: Train loss 0.802, Learning Rate 1.000e-05, It/sec 0.615, Tokens/sec 119.770, Trained Tokens 40223, Peak mem 4.624 GB
Iter 220: Train loss 0.776, Learning Rate 1.000e-05, It/sec 0.621, Tokens/sec 122.451, Trained Tokens 42194, Peak mem 4.624 GB
Iter 230: Train loss 0.677, Learning Rate 1.000e-05, It/sec 0.642, Tokens/sec 129.504, Trained Tokens 44212, Peak mem 4.624 GB
Iter 240: Train loss 0.586, Learning Rate 1.000e-05, It/sec 0.766, Tokens/sec 144.977, Trained Tokens 46104, Peak mem 4.624 GB
Iter 250: Train loss 0.623, Learning Rate 1.000e-05, It/sec 0.757, Tokens/sec 157.472, Trained Tokens 48185, Peak mem 4.624 GB
Iter 260: Train loss 0.523, Learning Rate 1.000e-05, It/sec 0.878, Tokens/sec 153.199, Trained Tokens 49929, Peak mem 4.624 GB
Iter 270: Train loss 0.528, Learning Rate 1.000e-05, It/sec 0.938, Tokens/sec 132.983, Trained Tokens 51347, Peak mem 4.624 GB
Iter 280: Train loss 0.518, Learning Rate 1.000e-05, It/sec 0.809, Tokens/sec 168.344, Trained Tokens 53428, Peak mem 4.624 GB
Iter 290: Train loss 0.531, Learning Rate 1.000e-05, It/sec 0.826, Tokens/sec 172.437, Trained Tokens 55516, Peak mem 4.624 GB
Iter 300: Train loss 0.512, Learning Rate 1.000e-05, It/sec 0.891, Tokens/sec 161.309, Trained Tokens 57327, Peak mem 4.624 GB
Iter 300: Saved adapter weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors and /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/0000300_adapters.safetensors.
Iter 310: Train loss 0.443, Learning Rate 1.000e-05, It/sec 0.868, Tokens/sec 158.630, Trained Tokens 59154, Peak mem 4.624 GB
Iter 320: Train loss 0.403, Learning Rate 1.000e-05, It/sec 0.746, Tokens/sec 166.507, Trained Tokens 61385, Peak mem 4.624 GB
Iter 330: Train loss 0.299, Learning Rate 1.000e-05, It/sec 0.810, Tokens/sec 157.442, Trained Tokens 63329, Peak mem 4.624 GB
Iter 340: Train loss 0.453, Learning Rate 1.000e-05, It/sec 0.717, Tokens/sec 169.434, Trained Tokens 65693, Peak mem 4.624 GB
Iter 350: Train loss 0.417, Learning Rate 1.000e-05, It/sec 0.792, Tokens/sec 163.304, Trained Tokens 67756, Peak mem 4.624 GB
Iter 360: Train loss 0.330, Learning Rate 1.000e-05, It/sec 0.766, Tokens/sec 156.709, Trained Tokens 69801, Peak mem 4.624 GB
Iter 370: Train loss 0.230, Learning Rate 1.000e-05, It/sec 0.921, Tokens/sec 143.695, Trained Tokens 71362, Peak mem 4.624 GB
Iter 380: Train loss 0.277, Learning Rate 1.000e-05, It/sec 0.869, Tokens/sec 143.384, Trained Tokens 73012, Peak mem 4.624 GB
Iter 390: Train loss 0.346, Learning Rate 1.000e-05, It/sec 0.710, Tokens/sec 167.089, Trained Tokens 75364, Peak mem 4.624 GB

Calculating loss...: 100%|██████████| 25/25 [00:15<00:00,  1.62it/s]

Iter 400: Val loss 0.315, Val took 15.443s
Iter 400: Train loss 0.259, Learning Rate 1.000e-05, It/sec 0.741, Tokens/sec 154.338, Trained Tokens 77446, Peak mem 4.624 GB
Iter 400: Saved adapter weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors and /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/0000400_adapters.safetensors.
Iter 410: Train loss 0.297, Learning Rate 1.000e-05, It/sec 0.631, Tokens/sec 191.810, Trained Tokens 80486, Peak mem 4.624 GB
Iter 420: Train loss 0.183, Learning Rate 1.000e-05, It/sec 0.861, Tokens/sec 153.041, Trained Tokens 82263, Peak mem 4.624 GB
Iter 430: Train loss 0.092, Learning Rate 1.000e-05, It/sec 0.975, Tokens/sec 151.298, Trained Tokens 83815, Peak mem 4.624 GB
Iter 440: Train loss 0.198, Learning Rate 1.000e-05, It/sec 0.929, Tokens/sec 150.050, Trained Tokens 85431, Peak mem 4.624 GB
Iter 450: Train loss 0.245, Learning Rate 1.000e-05, It/sec 0.652, Tokens/sec 176.093, Trained Tokens 88131, Peak mem 4.624 GB
Iter 460: Train loss 0.165, Learning Rate 1.000e-05, It/sec 0.784, Tokens/sec 161.460, Trained Tokens 90191, Peak mem 4.624 GB
Iter 470: Train loss 0.114, Learning Rate 1.000e-05, It/sec 0.847, Tokens/sec 146.497, Trained Tokens 91921, Peak mem 4.624 GB
Iter 480: Train loss 0.141, Learning Rate 1.000e-05, It/sec 0.742, Tokens/sec 188.661, Trained Tokens 94465, Peak mem 4.624 GB
Iter 490: Train loss 0.090, Learning Rate 1.000e-05, It/sec 0.906, Tokens/sec 138.441, Trained Tokens 95993, Peak mem 4.624 GB
Iter 500: Train loss 0.142, Learning Rate 1.000e-05, It/sec 0.732, Tokens/sec 166.311, Trained Tokens 98266, Peak mem 4.624 GB
Iter 500: Saved adapter weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors and /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/0000500_adapters.safetensors.
Iter 510: Train loss 0.055, Learning Rate 1.000e-05, It/sec 0.873, Tokens/sec 159.322, Trained Tokens 100092, Peak mem 4.624 GB
Iter 520: Train loss 0.092, Learning Rate 1.000e-05, It/sec 0.767, Tokens/sec 162.296, Trained Tokens 102207, Peak mem 4.624 GB
Iter 530: Train loss 0.113, Learning Rate 1.000e-05, It/sec 0.717, Tokens/sec 162.205, Trained Tokens 104470, Peak mem 4.624 GB
Iter 540: Train loss 0.104, Learning Rate 1.000e-05, It/sec 0.708, Tokens/sec 165.425, Trained Tokens 106805, Peak mem 4.624 GB
Iter 550: Train loss 0.067, Learning Rate 1.000e-05, It/sec 0.848, Tokens/sec 153.304, Trained Tokens 108612, Peak mem 4.624 GB
Iter 560: Train loss 0.048, Learning Rate 1.000e-05, It/sec 0.750, Tokens/sec 158.298, Trained Tokens 110723, Peak mem 4.624 GB
Iter 570: Train loss 0.050, Learning Rate 1.000e-05, It/sec 0.814, Tokens/sec 145.405, Trained Tokens 112509, Peak mem 4.624 GB
Iter 580: Train loss 0.025, Learning Rate 1.000e-05, It/sec 0.816, Tokens/sec 145.358, Trained Tokens 114290, Peak mem 4.624 GB
Iter 590: Train loss 0.032, Learning Rate 1.000e-05, It/sec 0.687, Tokens/sec 160.283, Trained Tokens 116622, Peak mem 4.624 GB

Calculating loss...: 100%|██████████| 25/25 [00:15<00:00,  1.64it/s]

Iter 600: Val loss 0.041, Val took 15.293s
Iter 600: Train loss 0.029, Learning Rate 1.000e-05, It/sec 0.690, Tokens/sec 159.015, Trained Tokens 118927, Peak mem 4.624 GB
Iter 600: Saved adapter weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors and /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/0000600_adapters.safetensors.
Iter 610: Train loss 0.016, Learning Rate 1.000e-05, It/sec 0.856, Tokens/sec 148.293, Trained Tokens 120659, Peak mem 4.624 GB
Iter 620: Train loss 0.041, Learning Rate 1.000e-05, It/sec 0.722, Tokens/sec 156.293, Trained Tokens 122824, Peak mem 4.624 GB
Iter 630: Train loss 0.008, Learning Rate 1.000e-05, It/sec 0.915, Tokens/sec 134.018, Trained Tokens 124288, Peak mem 4.624 GB
Iter 640: Train loss 0.018, Learning Rate 1.000e-05, It/sec 0.862, Tokens/sec 140.798, Trained Tokens 125922, Peak mem 4.624 GB
Iter 650: Train loss 0.011, Learning Rate 1.000e-05, It/sec 0.807, Tokens/sec 157.002, Trained Tokens 127868, Peak mem 4.624 GB
Iter 660: Train loss 0.011, Learning Rate 1.000e-05, It/sec 0.831, Tokens/sec 139.892, Trained Tokens 129552, Peak mem 4.624 GB
Iter 670: Train loss 0.014, Learning Rate 1.000e-05, It/sec 0.807, Tokens/sec 145.241, Trained Tokens 131351, Peak mem 4.624 GB
Iter 680: Train loss 0.003, Learning Rate 1.000e-05, It/sec 0.775, Tokens/sec 140.378, Trained Tokens 133163, Peak mem 4.624 GB
Iter 690: Train loss 0.008, Learning Rate 1.000e-05, It/sec 0.641, Tokens/sec 126.420, Trained Tokens 135135, Peak mem 4.624 GB
Iter 700: Train loss 0.010, Learning Rate 1.000e-05, It/sec 0.674, Tokens/sec 130.231, Trained Tokens 137068, Peak mem 4.624 GB
Iter 700: Saved adapter weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors and /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/0000700_adapters.safetensors.
Iter 710: Train loss 0.010, Learning Rate 1.000e-05, It/sec 0.780, Tokens/sec 109.306, Trained Tokens 138470, Peak mem 4.624 GB
Iter 720: Train loss 0.000, Learning Rate 1.000e-05, It/sec 0.808, Tokens/sec 131.182, Trained Tokens 140094, Peak mem 4.624 GB
Iter 730: Train loss 0.004, Learning Rate 1.000e-05, It/sec 0.790, Tokens/sec 155.096, Trained Tokens 142058, Peak mem 4.624 GB
Iter 740: Train loss 0.001, Learning Rate 1.000e-05, It/sec 0.970, Tokens/sec 139.155, Trained Tokens 143492, Peak mem 4.624 GB
Iter 750: Train loss 0.009, Learning Rate 1.000e-05, It/sec 0.787, Tokens/sec 152.615, Trained Tokens 145432, Peak mem 4.624 GB
Iter 760: Train loss 0.003, Learning Rate 1.000e-05, It/sec 0.845, Tokens/sec 155.891, Trained Tokens 147276, Peak mem 4.624 GB
Iter 770: Train loss 0.004, Learning Rate 1.000e-05, It/sec 0.860, Tokens/sec 138.652, Trained Tokens 148888, Peak mem 4.624 GB
Iter 780: Train loss 0.007, Learning Rate 1.000e-05, It/sec 0.901, Tokens/sec 141.519, Trained Tokens 150458, Peak mem 4.624 GB
Iter 790: Train loss 0.009, Learning Rate 1.000e-05, It/sec 0.830, Tokens/sec 126.053, Trained Tokens 151977, Peak mem 4.624 GB

Calculating loss...: 100%|██████████| 25/25 [00:14<00:00,  1.75it/s]

Iter 800: Val loss 0.022, Val took 14.321s
Iter 800: Train loss 0.001, Learning Rate 1.000e-05, It/sec 0.905, Tokens/sec 113.252, Trained Tokens 153229, Peak mem 4.624 GB
Iter 800: Saved adapter weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors and /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/0000800_adapters.safetensors.
Iter 810: Train loss 0.006, Learning Rate 1.000e-05, It/sec 0.632, Tokens/sec 146.534, Trained Tokens 155548, Peak mem 4.624 GB
Iter 820: Train loss 0.001, Learning Rate 1.000e-05, It/sec 0.854, Tokens/sec 133.763, Trained Tokens 157115, Peak mem 4.624 GB
Iter 830: Train loss 0.017, Learning Rate 1.000e-05, It/sec 0.668, Tokens/sec 148.743, Trained Tokens 159342, Peak mem 4.624 GB
Iter 840: Train loss 0.018, Learning Rate 1.000e-05, It/sec 0.550, Tokens/sec 151.594, Trained Tokens 162096, Peak mem 4.624 GB
Iter 850: Train loss 0.008, Learning Rate 1.000e-05, It/sec 0.696, Tokens/sec 150.066, Trained Tokens 164253, Peak mem 4.624 GB
Iter 860: Train loss 0.003, Learning Rate 1.000e-05, It/sec 0.847, Tokens/sec 135.757, Trained Tokens 165855, Peak mem 4.624 GB
Iter 870: Train loss 0.004, Learning Rate 1.000e-05, It/sec 0.756, Tokens/sec 148.155, Trained Tokens 167814, Peak mem 4.624 GB
Iter 880: Train loss 0.001, Learning Rate 1.000e-05, It/sec 0.879, Tokens/sec 137.857, Trained Tokens 169383, Peak mem 4.624 GB
Iter 890: Train loss 0.007, Learning Rate 1.000e-05, It/sec 0.747, Tokens/sec 150.578, Trained Tokens 171398, Peak mem 4.624 GB
Iter 900: Train loss 0.000, Learning Rate 1.000e-05, It/sec 0.763, Tokens/sec 109.593, Trained Tokens 172834, Peak mem 4.624 GB
Iter 900: Saved adapter weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors and /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/0000900_adapters.safetensors.
Iter 910: Train loss 0.005, Learning Rate 1.000e-05, It/sec 0.721, Tokens/sec 139.308, Trained Tokens 174765, Peak mem 4.624 GB
Iter 920: Train loss 0.002, Learning Rate 1.000e-05, It/sec 0.804, Tokens/sec 145.478, Trained Tokens 176575, Peak mem 4.624 GB
Iter 930: Train loss 0.005, Learning Rate 1.000e-05, It/sec 0.731, Tokens/sec 143.959, Trained Tokens 178544, Peak mem 4.624 GB
Iter 940: Train loss 0.005, Learning Rate 1.000e-05, It/sec 0.856, Tokens/sec 148.507, Trained Tokens 180278, Peak mem 4.624 GB
Iter 950: Train loss 0.005, Learning Rate 1.000e-05, It/sec 0.809, Tokens/sec 172.358, Trained Tokens 182408, Peak mem 4.624 GB
Iter 960: Train loss 0.010, Learning Rate 1.000e-05, It/sec 1.026, Tokens/sec 135.938, Trained Tokens 183733, Peak mem 4.624 GB
Iter 970: Train loss 0.002, Learning Rate 1.000e-05, It/sec 0.916, Tokens/sec 142.866, Trained Tokens 185293, Peak mem 4.624 GB
Iter 980: Train loss 0.003, Learning Rate 1.000e-05, It/sec 0.799, Tokens/sec 130.687, Trained Tokens 186928, Peak mem 4.624 GB
Iter 990: Train loss 0.004, Learning Rate 1.000e-05, It/sec 0.634, Tokens/sec 156.361, Trained Tokens 189393, Peak mem 4.624 GB

Calculating loss...: 100%|██████████| 25/25 [00:16<00:00,  1.53it/s]

Iter 1000: Val loss 0.023, Val took 16.346s
Iter 1000: Train loss 0.007, Learning Rate 1.000e-05, It/sec 0.702, Tokens/sec 151.624, Trained Tokens 191553, Peak mem 4.624 GB
Iter 1000: Saved adapter weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors and /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/0001000_adapters.safetensors.
Iter 1010: Train loss 0.004, Learning Rate 1.000e-05, It/sec 0.708, Tokens/sec 141.398, Trained Tokens 193551, Peak mem 4.624 GB
Iter 1020: Train loss 0.002, Learning Rate 1.000e-05, It/sec 0.720, Tokens/sec 146.283, Trained Tokens 195582, Peak mem 4.624 GB
Iter 1030: Train loss 0.003, Learning Rate 1.000e-05, It/sec 0.750, Tokens/sec 146.545, Trained Tokens 197537, Peak mem 4.624 GB
Iter 1040: Train loss 0.001, Learning Rate 1.000e-05, It/sec 0.658, Tokens/sec 135.418, Trained Tokens 199596, Peak mem 4.624 GB
Iter 1050: Train loss 0.004, Learning Rate 1.000e-05, It/sec 0.626, Tokens/sec 149.267, Trained Tokens 201982, Peak mem 4.624 GB
Iter 1060: Train loss 0.001, Learning Rate 1.000e-05, It/sec 0.708, Tokens/sec 147.361, Trained Tokens 204062, Peak mem 4.624 GB
Iter 1070: Train loss 0.006, Learning Rate 1.000e-05, It/sec 0.675, Tokens/sec 153.990, Trained Tokens 206344, Peak mem 4.624 GB
Iter 1080: Train loss 0.002, Learning Rate 1.000e-05, It/sec 0.796, Tokens/sec 132.862, Trained Tokens 208014, Peak mem 4.624 GB
Iter 1090: Train loss 0.001, Learning Rate 1.000e-05, It/sec 0.699, Tokens/sec 143.816, Trained Tokens 210070, Peak mem 4.624 GB
Iter 1100: Train loss 0.005, Learning Rate 1.000e-05, It/sec 0.585, Tokens/sec 149.881, Trained Tokens 212634, Peak mem 4.624 GB
Iter 1100: Saved adapter weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors and /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/0001100_adapters.safetensors.
Iter 1110: Train loss 0.002, Learning Rate 1.000e-05, It/sec 0.644, Tokens/sec 116.688, Trained Tokens 214446, Peak mem 4.624 GB
Iter 1120: Train loss 0.004, Learning Rate 1.000e-05, It/sec 0.683, Tokens/sec 143.264, Trained Tokens 216544, Peak mem 4.624 GB
Iter 1130: Train loss 0.000, Learning Rate 1.000e-05, It/sec 0.940, Tokens/sec 115.208, Trained Tokens 217770, Peak mem 4.624 GB
Iter 1140: Train loss 0.001, Learning Rate 1.000e-05, It/sec 0.794, Tokens/sec 148.794, Trained Tokens 219643, Peak mem 4.624 GB
Iter 1150: Train loss 0.007, Learning Rate 1.000e-05, It/sec 0.623, Tokens/sec 159.493, Trained Tokens 222205, Peak mem 4.624 GB
Iter 1160: Train loss 0.009, Learning Rate 1.000e-05, It/sec 0.604, Tokens/sec 156.888, Trained Tokens 224803, Peak mem 4.624 GB
Iter 1170: Train loss 0.000, Learning Rate 1.000e-05, It/sec 0.843, Tokens/sec 121.961, Trained Tokens 226250, Peak mem 4.624 GB
Iter 1180: Train loss 0.003, Learning Rate 1.000e-05, It/sec 0.709, Tokens/sec 147.031, Trained Tokens 228323, Peak mem 4.624 GB
Iter 1190: Train loss 0.000, Learning Rate 1.000e-05, It/sec 0.874, Tokens/sec 127.223, Trained Tokens 229779, Peak mem 4.624 GB

Calculating loss...: 100%|██████████| 25/25 [00:14<00:00,  1.69it/s]

Iter 1200: Val loss 0.000, Val took 14.774s
Iter 1200: Train loss 0.003, Learning Rate 1.000e-05, It/sec 0.740, Tokens/sec 139.406, Trained Tokens 231664, Peak mem 4.624 GB
Iter 1200: Saved adapter weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors and /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/0001200_adapters.safetensors.
Iter 1210: Train loss 0.000, Learning Rate 1.000e-05, It/sec 0.749, Tokens/sec 133.870, Trained Tokens 233452, Peak mem 4.624 GB
Iter 1220: Train loss 0.006, Learning Rate 1.000e-05, It/sec 0.639, Tokens/sec 141.632, Trained Tokens 235670, Peak mem 4.624 GB
Iter 1230: Train loss 0.003, Learning Rate 1.000e-05, It/sec 0.770, Tokens/sec 138.912, Trained Tokens 237475, Peak mem 4.624 GB
Iter 1240: Train loss 0.000, Learning Rate 1.000e-05, It/sec 0.652, Tokens/sec 121.059, Trained Tokens 239333, Peak mem 4.624 GB
Iter 1250: Train loss 0.006, Learning Rate 1.000e-05, It/sec 0.579, Tokens/sec 130.926, Trained Tokens 241593, Peak mem 4.624 GB
Iter 1260: Train loss 0.000, Learning Rate 1.000e-05, It/sec 0.797, Tokens/sec 131.287, Trained Tokens 243241, Peak mem 4.624 GB
Iter 1270: Train loss 0.003, Learning Rate 1.000e-05, It/sec 0.621, Tokens/sec 147.049, Trained Tokens 245609, Peak mem 4.624 GB
Iter 1280: Train loss 0.000, Learning Rate 1.000e-05, It/sec 0.885, Tokens/sec 130.045, Trained Tokens 247078, Peak mem 4.624 GB
Iter 1290: Train loss 0.001, Learning Rate 1.000e-05, It/sec 0.831, Tokens/sec 130.521, Trained Tokens 248649, Peak mem 4.624 GB
Iter 1300: Train loss 0.001, Learning Rate 1.000e-05, It/sec 0.746, Tokens/sec 135.540, Trained Tokens 250466, Peak mem 4.624 GB
Iter 1300: Saved adapter weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors and /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/0001300_adapters.safetensors.
Iter 1310: Train loss 0.000, Learning Rate 1.000e-05, It/sec 0.793, Tokens/sec 134.726, Trained Tokens 252165, Peak mem 4.624 GB
Iter 1320: Train loss 0.000, Learning Rate 1.000e-05, It/sec 0.775, Tokens/sec 131.457, Trained Tokens 253862, Peak mem 4.624 GB
Iter 1330: Train loss 0.001, Learning Rate 1.000e-05, It/sec 0.703, Tokens/sec 155.385, Trained Tokens 256071, Peak mem 4.624 GB
Iter 1340: Train loss 0.002, Learning Rate 1.000e-05, It/sec 0.761, Tokens/sec 136.275, Trained Tokens 257861, Peak mem 4.624 GB
Iter 1350: Train loss 0.001, Learning Rate 1.000e-05, It/sec 0.773, Tokens/sec 144.252, Trained Tokens 259727, Peak mem 4.624 GB
Iter 1360: Train loss 0.000, Learning Rate 1.000e-05, It/sec 0.629, Tokens/sec 147.165, Trained Tokens 262068, Peak mem 4.624 GB
Iter 1370: Train loss 0.001, Learning Rate 1.000e-05, It/sec 0.663, Tokens/sec 153.529, Trained Tokens 264382, Peak mem 4.624 GB
Iter 1380: Train loss 0.008, Learning Rate 1.000e-05, It/sec 0.653, Tokens/sec 171.182, Trained Tokens 267002, Peak mem 4.624 GB
Iter 1390: Train loss 0.002, Learning Rate 1.000e-05, It/sec 0.718, Tokens/sec 168.446, Trained Tokens 269347, Peak mem 4.624 GB

Calculating loss...: 100%|██████████| 25/25 [00:15<00:00,  1.58it/s]

Iter 1400: Val loss 0.001, Val took 15.790s
Iter 1400: Train loss 0.002, Learning Rate 1.000e-05, It/sec 0.770, Tokens/sec 133.968, Trained Tokens 271087, Peak mem 4.624 GB
Iter 1400: Saved adapter weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors and /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/0001400_adapters.safetensors.
Iter 1410: Train loss 0.000, Learning Rate 1.000e-05, It/sec 0.917, Tokens/sec 109.935, Trained Tokens 272286, Peak mem 4.624 GB
Iter 1420: Train loss 0.005, Learning Rate 1.000e-05, It/sec 0.670, Tokens/sec 139.516, Trained Tokens 274368, Peak mem 4.624 GB
Iter 1430: Train loss 0.000, Learning Rate 1.000e-05, It/sec 0.683, Tokens/sec 113.464, Trained Tokens 276029, Peak mem 4.624 GB
Iter 1440: Train loss 0.002, Learning Rate 1.000e-05, It/sec 0.641, Tokens/sec 141.576, Trained Tokens 278239, Peak mem 4.624 GB
Iter 1450: Train loss 0.001, Learning Rate 1.000e-05, It/sec 0.814, Tokens/sec 134.990, Trained Tokens 279897, Peak mem 4.624 GB
Iter 1460: Train loss 0.003, Learning Rate 1.000e-05, It/sec 0.649, Tokens/sec 144.231, Trained Tokens 282120, Peak mem 4.624 GB
Iter 1470: Train loss 0.001, Learning Rate 1.000e-05, It/sec 0.689, Tokens/sec 130.604, Trained Tokens 284016, Peak mem 4.624 GB
Iter 1480: Train loss 0.004, Learning Rate 1.000e-05, It/sec 0.686, Tokens/sec 143.582, Trained Tokens 286109, Peak mem 4.624 GB
Iter 1490: Train loss 0.004, Learning Rate 1.000e-05, It/sec 0.713, Tokens/sec 141.926, Trained Tokens 288100, Peak mem 4.624 GB

Calculating loss...: 100%|██████████| 25/25 [00:18<00:00,  1.35it/s]

Iter 1500: Val loss 0.013, Val took 18.507s
Iter 1500: Train loss 0.000, Learning Rate 1.000e-05, It/sec 0.808, Tokens/sec 110.913, Trained Tokens 289473, Peak mem 4.624 GB
Iter 1500: Saved adapter weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors and /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/0001500_adapters.safetensors.
Saved final weights to /Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/results/fine_tunes/qwen3_1_7b_lora/algorithmic_scaffold_v3_5_lora12/adapters/adapters.safetensors.

## Validation Accuracy

Use these cells after training to evaluate the adapters on validation data. This is the right split for choosing LoRA hyperparameters. The frozen `benchmark/data/test` split should be used only after the setup is chosen.

Validation is closed-book: the prompt contains only the problem, not the training reasoning. Metrics are reported separately for binary true/false-style tasks and non-binary short-answer tasks.

In [25]:
from mlx_lm import generate, load
from tqdm.auto import tqdm

/Users/xingzheli/Documents/Python-WorkSpace/SC_fine-tune/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [26]:
import importlib
import training_eval.eval_utils as eval_utils

importlib.reload(eval_utils)

GRADING_POLICY = eval_utils.GRADING_POLICY
balanced_eval_subset = eval_utils.balanced_eval_subset
extract_answer = eval_utils.extract_answer
extract_json_object = eval_utils.extract_json_object
is_correct = eval_utils.is_correct
load_jsonl_records = eval_utils.load_jsonl_records
rows_to_frame = eval_utils.rows_to_frame
save_results = eval_utils.save_results
summarize_accuracy = eval_utils.summarize_accuracy

In [27]:
VAL_RECORDS = {
    "formula_direct": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "val_formula_direct"),
    "algorithmic_scaffold": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "val_algorithmic_scaffold"),
    "algorithmic_scaffold_v2": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "val_algorithmic_scaffold_v2"),
    "algorithmic_scaffold_v2_5": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "val_algorithmic_scaffold_v2_5"),
    "algorithmic_scaffold_v3": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "val_algorithmic_scaffold_v3"),
    "algorithmic_scaffold_v3_1": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "val_algorithmic_scaffold_v3_1"),
    "algorithmic_scaffold_v3_1_lora8": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "val_algorithmic_scaffold_v3_1"),
    "algorithmic_scaffold_v3_5": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "val_algorithmic_scaffold_v3_5"),
    "algorithmic_scaffold_v3_5_lora12": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "val_algorithmic_scaffold_v3_5"),
}

VALIDATION_RESULT_ROOT = PROJECT_ROOT / "results" / "fine_tunes" / "qwen3_1_7b_lora_validation"
VALIDATION_LIMIT = None
RESET_VALIDATION_OUTPUTS = True
MAX_NEW_TOKENS = 512

In [28]:
FINE_TUNE_SYSTEM_MESSAGE = 'You solve discrete stochastic-process problems. Give concise reasoning, then end with exactly one final answer block: Final answer:\n<answer>\n{...}\n</answer>. Do not write anything after </answer>.'

In [29]:
def make_fine_tuned_chat_messages(problem):
    return [
        {"role": "system", "content": FINE_TUNE_SYSTEM_MESSAGE},
        {"role": "user", "content": problem},
    ]

In [30]:
def make_qwen_prompt(tokenizer, problem):
    messages = make_fine_tuned_chat_messages(problem)
    try:
        return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True, enable_thinking=False)
    except TypeError:
        return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

In [31]:
def load_adapter_model(adapter_path):
    return load(MODEL_NAME, adapter_path=str(adapter_path))

In [32]:
def generate_validation_answer(model, tokenizer, problem):
    prompt = make_qwen_prompt(tokenizer, problem)
    return generate(model, tokenizer, prompt=prompt, max_tokens=MAX_NEW_TOKENS, verbose=False)

In [33]:
def validation_result_dir(adapter_label):
    suffix = "full" if VALIDATION_LIMIT is None else f"subset_{VALIDATION_LIMIT}"
    return VALIDATION_RESULT_ROOT / f"{adapter_label}_{suffix}"

In [34]:
def validation_outputs_path(adapter_label):
    return validation_result_dir(adapter_label) / "outputs.jsonl"

In [35]:
def reset_validation_outputs(adapter_label):
    result_dir = validation_result_dir(adapter_label)
    for filename in ["outputs.jsonl", "outputs.csv", "metrics.json"]:
        path = result_dir / filename
        if path.exists():
            path.unlink()

In [36]:
def load_validation_cached_rows(adapter_label):
    path = validation_outputs_path(adapter_label)
    if not path.exists():
        return []
    rows_by_id = {}
    with path.open() as f:
        for line in f:
            if line.strip():
                row = json.loads(line)
                rows_by_id[row["id"]] = row
    return list(rows_by_id.values())

In [37]:
def append_validation_row(adapter_label, row):
    result_dir = validation_result_dir(adapter_label)
    result_dir.mkdir(parents=True, exist_ok=True)
    with validation_outputs_path(adapter_label).open("a") as f:
        f.write(json.dumps(row, sort_keys=True) + "\n")

In [38]:
def evaluate_adapter_on_validation(adapter_label, config):
    if RESET_VALIDATION_OUTPUTS:
        reset_validation_outputs(adapter_label)

    model, tokenizer = load_adapter_model(config["adapter_path"])
    records = balanced_eval_subset(VAL_RECORDS[adapter_label], VALIDATION_LIMIT)
    rows = load_validation_cached_rows(adapter_label)
    completed_ids = {row["id"] for row in rows}

    for record in tqdm(records, desc=f"val/{adapter_label}"):
        if record["id"] in completed_ids:
            continue

        raw_output = generate_validation_answer(model, tokenizer, record["problem"])
        predicted = extract_answer(raw_output, record["canonical_answer"])
        metadata = record.get("metadata", {})

        row = {
            "adapter": adapter_label,
            "id": record["id"],
            "family": record["family"],
            "problem_type": record["problem_type"],
            "difficulty": record["difficulty"],
            "answer_type": record["answer_type"],
            "manual_variation": metadata.get("manual_variation", False),
            "problem": record["problem"],
            "canonical_answer": record["canonical_answer"],
            "raw_output": raw_output,
            "predicted_answer": predicted,
            "correct": is_correct(predicted, record["canonical_answer"]),
        }
        append_validation_row(adapter_label, row)
        rows.append(row)

    return rows

In [39]:
def save_validation_results(adapter_label, rows):
    df = rows_to_frame(rows)
    metrics = summarize_accuracy(df)
    metrics.update({
        "model": MODEL_NAME,
        "adapter": adapter_label,
        "dataset": "benchmark/data/val or benchmark/data/val_implicit_theorems",
        "validation_limit": VALIDATION_LIMIT,
        "split_role": "validation_for_hyperparameter_selection",
        "grading_policy": GRADING_POLICY,
    })
    return save_results(rows, validation_result_dir(adapter_label), metrics)

In [40]:
validation_rows = []

for adapter_label, config in ACTIVE_EXPERIMENTS.items():
    rows = evaluate_adapter_on_validation(adapter_label, config)
    save_validation_results(adapter_label, rows)
    validation_rows.extend(rows)

val_df = rows_to_frame(validation_rows)
val_df.head()

Fetching 7 files: 100%|██████████| 7/7 [00:00<00:00, 120823.57it/s]
val/algorithmic_scaffold_v3_5_lora12: 100%|██████████| 240/240 [31:12<00:00,  7.80s/it]

,adapter,id,family,problem_type,difficulty,answer_type,manual_variation,problem,canonical_answer,raw_output,predicted_answer,correct
0,algorithmic_scaffold_v3_5_lora12,hitting_time_expectation_val_441000,hitting_time_expectation,symmetric_boundaries_zero_a,1,non_binary,True,Consider a simple symmetric random walk (X_n) ...,{'expected_time': '9'},Step 1: Identify the walk type.\nThe walk is s...,{'expected_time': '9'},True
1,algorithmic_scaffold_v3_5_lora12,hitting_time_expectation_val_441001,hitting_time_expectation,symmetric_boundaries_zero_a,1,non_binary,False,Let (S_n) be a simple symmetric random walk on...,{'expected_time': '3'},Step 1: Identify the walk type.\nThe walk is s...,{'expected_time': '3'},True
2,algorithmic_scaffold_v3_5_lora12,hitting_time_expectation_val_441002,hitting_time_expectation,symmetric_boundaries_zero_a,1,non_binary,False,Let (X_n) be a simple symmetric random walk on...,{'expected_time': '16'},Step 1: Identify the walk type.\nThe walk is s...,{'expected_time': '16'},True
3,algorithmic_scaffold_v3_5_lora12,hitting_time_expectation_val_441003,hitting_time_expectation,symmetric_boundaries_zero_a,1,non_binary,False,Let (S_n) be a simple symmetric random walk on...,{'expected_time': '12'},Step 1: Identify the walk type.\nThe walk is s...,{'expected_time': '12'},True
4,algorithmic_scaffold_v3_5_lora12,hitting_time_expectation_val_441004,hitting_time_expectation,symmetric_boundaries_zero_a,1,non_binary,False,Let (X_n) be a simple symmetric random walk on...,{'expected_time': '8'},Step 1: Identify the walk type.\nThe walk is s...,{'expected_time': '8'},True

In [41]:
display(val_df.groupby("adapter")["correct"].agg(["mean", "sum", "count"]).sort_index())
display(val_df.groupby(["adapter", "answer_type"])["correct"].agg(["mean", "sum", "count"]).sort_index())
display(val_df.groupby(["adapter", "family"])["correct"].agg(["mean", "sum", "count"]).sort_index())
display(val_df.groupby(["adapter", "difficulty"])["correct"].agg(["mean", "sum", "count"]).sort_index())

                                      mean  sum  count
adapter
algorithmic_scaffold_v3_5_lora12  0.920833  221    240

                                                  mean  sum  count
adapter                          answer_type
algorithmic_scaffold_v3_5_lora12 binary       0.900000  108    120
                                 non_binary   0.941667  113    120

                                                                  mean  sum  \
adapter                          family
algorithmic_scaffold_v3_5_lora12 hitting_time_expectation     0.883333   53
                                 martingale_verification      0.950000   57
                                 optional_stopping_validity   0.850000   51
                                 stopped_process_expectation  1.000000   60

                                                              count
adapter                          family
algorithmic_scaffold_v3_5_lora12 hitting_time_expectation        60
                                 martingale_verification         60
                                 optional_stopping_validity      60
                                 stopped_process_expectation     60

                                               mean  sum  count
adapter                          difficulty
algorithmic_scaffold_v3_5_lora12 1           0.9375   75     80
                                 2           0.9375   75     80
                                 3           0.8875   71     80

In [42]:
val_df.loc[
    ~val_df["correct"],
    ["adapter", "id", "answer_type", "family", "problem_type", "difficulty", "canonical_answer", "predicted_answer", "raw_output"],
].head(30)

,adapter,id,answer_type,family,problem_type,difficulty,canonical_answer,predicted_answer,raw_output
25,algorithmic_scaffold_v3_5_lora12,hitting_time_expectation_val_442005,non_binary,hitting_time_expectation,symmetric_shifted_boundaries,2,{'expected_time': '15'},{'expected_time': '20'},Step 1: Identify the walk type.\nThe walk is s...
40,algorithmic_scaffold_v3_5_lora12,hitting_time_expectation_val_443000,non_binary,hitting_time_expectation,biased_boundaries_zero_a,3,{'expected_time': '11/5'},{'expected_time': '67/5'},Step 1: Classify the walk and choose the biase...
41,algorithmic_scaffold_v3_5_lora12,hitting_time_expectation_val_443001,non_binary,hitting_time_expectation,biased_boundaries_zero_a,3,{'expected_time': '43/7'},{'expected_time': '69/7'},Step 1: Classify the walk and choose the biase...
50,algorithmic_scaffold_v3_5_lora12,hitting_time_expectation_val_443010,non_binary,hitting_time_expectation,biased_boundaries_zero_a,3,{'expected_time': '147/31'},{'expected_time': '1356'},Step 1: Classify the walk and choose the biase...
52,algorithmic_scaffold_v3_5_lora12,hitting_time_expectation_val_443012,non_binary,hitting_time_expectation,biased_boundaries_zero_a,3,{'expected_time': '33/13'},{'expected_time': '-18985/1435'},Step 1: Classify the walk and choose the biase...
54,algorithmic_scaffold_v3_5_lora12,hitting_time_expectation_val_443014,non_binary,hitting_time_expectation,biased_boundaries_zero_a,3,{'expected_time': '14990/2059'},{'expected_time': '15000/2059'},Step 1: Classify the walk and choose the biase...
57,algorithmic_scaffold_v3_5_lora12,hitting_time_expectation_val_443017,non_binary,hitting_time_expectation,biased_boundaries_zero_a,3,{'expected_time': '1254/127'},{'expected_time': '636/127'},Step 1: Classify the walk and choose the biase...
65,algorithmic_scaffold_v3_5_lora12,martingale_verification_val_411005,binary,martingale_verification,centered_walk_basic,1,{'is_martingale': True},{'type': 'string'},Step 1: Identify the martingale test.\nCheck w...
75,algorithmic_scaffold_v3_5_lora12,martingale_verification_val_411015,binary,martingale_verification,centered_walk_basic,1,{'is_martingale': True},"{'tag': 'is_martingale', 'value': True}",Step 1: Identify the martingale test.\nCheck w...
85,algorithmic_scaffold_v3_5_lora12,martingale_verification_val_412005,binary,martingale_verification,quadratic_compensation,2,{'is_martingale': True},"{'prop_c': '25', 'req_c': '25'}",Step 1: Use only the compensation comparison.\...
120,algorithmic_scaffold_v3_5_lora12,optional_stopping_validity_val_421000,binary,optional_stopping_validity,bounded_time_valid,1,{'valid': True},"{'is_juiced': False, 'required': True, 'exactl...",Step 1: Check the optional-stopping condition....
125,algorithmic_scaffold_v3_5_lora12,optional_stopping_validity_val_421005,binary,optional_stopping_validity,bounded_time_valid,1,{'valid': True},None,Step 1: Check the optional-stopping condition....
135,algorithmic_scaffold_v3_5_lora12,optional_stopping_validity_val_421015,binary,optional_stopping_validity,bounded_time_valid,1,{'valid': True},"{'is_juiced': False, 'required': True, 'option...",Step 1: Check the optional-stopping condition....
140,algorithmic_scaffold_v3_5_lora12,optional_stopping_validity_val_422000,binary,optional_stopping_validity,unbounded_first_hit_invalid,2,{'valid': False},"{'is_juiced': False, 'required': False, 'optio...",Step 1: Check the optional-stopping condition....
150,algorithmic_scaffold_v3_5_lora12,optional_stopping_validity_val_422010,binary,optional_stopping_validity,unbounded_first_hit_invalid,2,{'valid': False},"{'is_juiced': False, 'required': False, 'optio...",Step 1: Check the optional-stopping condition....
155,algorithmic_scaffold_v3_5_lora12,optional_stopping_validity_val_422015,binary,optional_stopping_validity,unbounded_first_hit_invalid,2,{'valid': False},{'step_1': 'Check the optional-stopping condit...,Step 1: Check the optional-stopping condition....
160,algorithmic_scaffold_v3_5_lora12,optional_stopping_validity_val_423000,binary,optional_stopping_validity,unbounded_first_hit_invalid,3,{'valid': False},"{'is_juiced': False, 'required': False, 'optio...",Step 1: Check the optional-stopping condition....
165,algorithmic_scaffold_v3_5_lora12,optional_stopping_validity_val_423005,binary,optional_stopping_validity,unbounded_first_hit_invalid,3,{'valid': False},None,Step 1: Check the optional-stopping condition....
175,algorithmic_scaffold_v3_5_lora12,optional_stopping_validity_val_423015,binary,optional_stopping_validity,unbounded_first_hit_invalid,3,{'valid': False},"{'unjustified': True, 'no': True}",Step 1: Check the optional-stopping condition....

## Train Generation Diagnostic

Use this to distinguish overfitting from underfitting. It evaluates the trained adapters by generation on a balanced sample from the training split, using the same prompt and grader as validation. If train generation is also weak, the adapter is not yet learning the task; if train generation is strong but validation is weak, it is overfitting.

In [43]:
TRAIN_RECORDS = {
    "formula_direct": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "train_formula_direct"),
    "algorithmic_scaffold": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "train_algorithmic_scaffold"),
    "algorithmic_scaffold_v2": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "train_algorithmic_scaffold_v2"),
    "algorithmic_scaffold_v2_5": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "train_algorithmic_scaffold_v2_5"),
    "algorithmic_scaffold_v3": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "train_algorithmic_scaffold_v3"),
    "algorithmic_scaffold_v3_1": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "train_algorithmic_scaffold_v3_1"),
    "algorithmic_scaffold_v3_1_lora8": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "train_algorithmic_scaffold_v3_1"),
    "algorithmic_scaffold_v3_5": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "train_algorithmic_scaffold_v3_5"),
    "algorithmic_scaffold_v3_5_lora12": load_jsonl_records(PROJECT_ROOT / "benchmark" / "data" / "train_algorithmic_scaffold_v3_5"),
}

TRAIN_DIAGNOSTIC_RESULT_ROOT = PROJECT_ROOT / "results" / "fine_tunes" / "qwen3_1_7b_lora_train_diagnostic"
TRAIN_DIAGNOSTIC_LIMIT = 120
RESET_TRAIN_DIAGNOSTIC_OUTPUTS = True

In [44]:
def train_diagnostic_result_dir(adapter_label):
    suffix = "full" if TRAIN_DIAGNOSTIC_LIMIT is None else f"subset_{TRAIN_DIAGNOSTIC_LIMIT}"
    return TRAIN_DIAGNOSTIC_RESULT_ROOT / f"{adapter_label}_{suffix}"

In [45]:
def train_diagnostic_outputs_path(adapter_label):
    return train_diagnostic_result_dir(adapter_label) / "outputs.jsonl"

In [46]:
def reset_train_diagnostic_outputs(adapter_label):
    result_dir = train_diagnostic_result_dir(adapter_label)
    for filename in ["outputs.jsonl", "outputs.csv", "metrics.json"]:
        path = result_dir / filename
        if path.exists():
            path.unlink()

In [47]:
def load_train_diagnostic_cached_rows(adapter_label):
    path = train_diagnostic_outputs_path(adapter_label)
    if not path.exists():
        return []
    rows_by_id = {}
    with path.open() as f:
        for line in f:
            if line.strip():
                row = json.loads(line)
                rows_by_id[row["id"]] = row
    return list(rows_by_id.values())

In [48]:
def append_train_diagnostic_row(adapter_label, row):
    result_dir = train_diagnostic_result_dir(adapter_label)
    result_dir.mkdir(parents=True, exist_ok=True)
    with train_diagnostic_outputs_path(adapter_label).open("a") as f:
        f.write(json.dumps(row, sort_keys=True) + "\n")

In [49]:
def evaluate_adapter_on_train_diagnostic(adapter_label, config):
    if RESET_TRAIN_DIAGNOSTIC_OUTPUTS:
        reset_train_diagnostic_outputs(adapter_label)

    model, tokenizer = load_adapter_model(config["adapter_path"])
    records = balanced_eval_subset(TRAIN_RECORDS[adapter_label], TRAIN_DIAGNOSTIC_LIMIT)
    rows = load_train_diagnostic_cached_rows(adapter_label)
    completed_ids = {row["id"] for row in rows}

    for record in tqdm(records, desc=f"train/{adapter_label}"):
        if record["id"] in completed_ids:
            continue

        raw_output = generate_validation_answer(model, tokenizer, record["problem"])
        predicted = extract_answer(raw_output, record["canonical_answer"])
        metadata = record.get("metadata", {})

        row = {
            "adapter": adapter_label,
            "id": record["id"],
            "family": record["family"],
            "problem_type": record["problem_type"],
            "difficulty": record["difficulty"],
            "answer_type": record["answer_type"],
            "manual_variation": metadata.get("manual_variation", False),
            "problem": record["problem"],
            "canonical_answer": record["canonical_answer"],
            "raw_output": raw_output,
            "predicted_answer": predicted,
            "correct": is_correct(predicted, record["canonical_answer"]),
        }
        append_train_diagnostic_row(adapter_label, row)
        rows.append(row)

    return rows

In [50]:
def save_train_diagnostic_results(adapter_label, rows):
    df = rows_to_frame(rows)
    metrics = summarize_accuracy(df)
    metrics.update({
        "model": MODEL_NAME,
        "adapter": adapter_label,
        "dataset": "benchmark/data/train or benchmark/data/train_implicit_theorems",
        "train_diagnostic_limit": TRAIN_DIAGNOSTIC_LIMIT,
        "split_role": "train_generation_diagnostic",
        "grading_policy": GRADING_POLICY,
    })
    return save_results(rows, train_diagnostic_result_dir(adapter_label), metrics)

In [51]:
RUN_TRAIN_DIAGNOSTIC = True

train_diagnostic_rows = []

if RUN_TRAIN_DIAGNOSTIC:
    for adapter_label, config in ACTIVE_EXPERIMENTS.items():
        rows = evaluate_adapter_on_train_diagnostic(adapter_label, config)
        save_train_diagnostic_results(adapter_label, rows)
        train_diagnostic_rows.extend(rows)

train_df = rows_to_frame(train_diagnostic_rows)
train_df.head()

Fetching 7 files: 100%|██████████| 7/7 [00:00<00:00, 159565.91it/s]
train/algorithmic_scaffold_v3_5_lora12: 100%|██████████| 120/120 [16:25<00:00,  8.21s/it]

,adapter,id,family,problem_type,difficulty,answer_type,manual_variation,problem,canonical_answer,raw_output,predicted_answer,correct
0,algorithmic_scaffold_v3_5_lora12,hitting_time_expectation_train_5220006,hitting_time_expectation,biased_boundaries_zero_a,3,non_binary,False,Let (S_n) be a nearest-neighbor random walk on...,{'expected_time': '1100/133'},Step 1: Classify the walk and choose the biase...,{'expected_time': '1100/133'},True
1,algorithmic_scaffold_v3_5_lora12,hitting_time_expectation_train_5200000,hitting_time_expectation,symmetric_boundaries_zero_a,1,non_binary,False,Let (S_n) be a simple symmetric random walk on...,{'expected_time': '32'},Step 1: Identify the walk type.\nThe walk is s...,{'expected_time': '32'},True
2,algorithmic_scaffold_v3_5_lora12,hitting_time_expectation_train_5210000,hitting_time_expectation,symmetric_shifted_boundaries,2,non_binary,False,Let (S_n) be a simple symmetric random walk wi...,{'expected_time': '4'},Step 1: Identify the walk type.\nThe walk is s...,{'expected_time': '4'},True
3,algorithmic_scaffold_v3_5_lora12,martingale_verification_train_5600000,martingale_verification,centered_walk_basic,1,binary,False,"Let S_0 = 0 and S_n = Y_1 + ... + Y_n, where t...",{'is_martingale': True},Step 1: Identify the martingale test.\nCheck w...,{'is_martingale': True},True
4,algorithmic_scaffold_v3_5_lora12,martingale_verification_train_5620003,martingale_verification,exponential_compensation,3,binary,False,"Let S_n = Y_1 + ... + Y_n, where the Y_k are i...",{'is_martingale': False},Step 1: Use only the denominator-factor compar...,{'is_martingale': False},True

In [52]:
display(train_df.groupby("adapter")["correct"].agg(["mean", "sum", "count"]).sort_index())
display(train_df.groupby(["adapter", "answer_type"])["correct"].agg(["mean", "sum", "count"]).sort_index())
display(train_df.groupby(["adapter", "family"])["correct"].agg(["mean", "sum", "count"]).sort_index())
display(train_df.groupby(["adapter", "problem_type"])["correct"].agg(["mean", "sum", "count"]).sort_index())

                                   mean  sum  count
adapter
algorithmic_scaffold_v3_5_lora12  0.975  117    120

                                              mean  sum  count
adapter                          answer_type
algorithmic_scaffold_v3_5_lora12 binary       1.00   60     60
                                 non_binary   0.95   57     60

                                                              mean  sum  count
adapter                          family
algorithmic_scaffold_v3_5_lora12 hitting_time_expectation      0.9   27     30
                                 martingale_verification       1.0   30     30
                                 optional_stopping_validity    1.0   30     30
                                 stopped_process_expectation   1.0   30     30

                                                               mean  sum  \
adapter                          problem_type
algorithmic_scaffold_v3_5_lora12 biased_boundaries_zero_a       0.7    7
                                 bounded_time_valid             1.0   10
                                 bounded_walk_expectation       1.0   10
                                 centered_walk_basic            1.0   10
                                 exponential_compensation       1.0   10
                                 finite_state_hitting_valid     1.0   10
                                 quadratic_compensation         1.0   10
                                 quadratic_fixed_horizon        1.0   10
                                 stopped_martingale_value       1.0   10
                                 symmetric_boundaries_zero_a    1.0   10
                                 symmetric_shifted_boundaries   1.0   10
                                 unbounded_first_hit_invalid    1.0   10

                                                               count
adapter                          problem_type
algorithmic_scaffold_v3_5_lora12 biased_boundaries_zero_a         10
                                 bounded_time_valid               10
                                 bounded_walk_expectation         10
                                 centered_walk_basic              10
                                 exponential_compensation         10
                                 finite_state_hitting_valid       10
                                 quadratic_compensation           10
                                 quadratic_fixed_horizon          10
                                 stopped_martingale_value         10
                                 symmetric_boundaries_zero_a      10
                                 symmetric_shifted_boundaries     10
                                 unbounded_first_hit_invalid      10